using from './dashboard/annotations';
using from './sales/annotations';
using from './purchases/annotations';
using from './finance/annotations';
using from './settings/annotations';
using from './taxadvisor/annotations';
using from './support/annotations';
using from './reports/annotations';
using from './clients/annotations';
