name: Website build

on:
  pull_request:
    paths:
      - 'website/**'
      - '.github/workflows/website-build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.GH_ACTION_NODEJS_VERSION || '24' }}

      - name: Clean install node packages
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Build
        run: npm run build
